const servicesData = [
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Hair Cutting",
      businessName: "John's Salon",
      city: "Mumbai",
      timings: "10:00 AM - 8:00 PM",
      price: "20.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Plumbing",
      businessName: "QuickFix Plumbing",
      city: "Delhi",
      timings: "9:00 AM - 6:00 PM",
      price: "15.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Electrical Work",
      businessName: "Electric Pro",
      city: "Mumbai",
      timings: "10:00 AM - 8:00 PM",
      price: "25.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Car Repair",
      businessName: "AutoCare Garage",
      city: "Pune",
      timings: "9:00 AM - 7:00 PM",
      price: "50.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Home Cleaning",
      businessName: "SparkleClean Services",
      city: "Delhi",
      timings: "8:00 AM - 6:00 PM",
      price: "40.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Carpentry",
      businessName: "WoodWorks",
      city: "Bangalore",
      timings: "10:00 AM - 5:00 PM",
      price: "30.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Hair Cutting",
      businessName: "Style Studio",
      city: "Delhi",
      timings: "10:00 AM - 8:00 PM",
      price: "20.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Plumbing",
      businessName: "FlowFix",
      city: "Mumbai",
      timings: "9:00 AM - 6:00 PM",
      price: "15.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Electrical Work",
      businessName: "PowerFix Solutions",
      city: "Bangalore",
      timings: "10:00 AM - 8:00 PM",
      price: "25.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Car Repair",
      businessName: "Speedy Garage",
      city: "Delhi",
      timings: "9:00 AM - 7:00 PM",
      price: "50.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Home Cleaning",
      businessName: "CleanSpace",
      city: "Mumbai",
      timings: "8:00 AM - 6:00 PM",
      price: "40.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Carpentry",
      businessName: "TimberMasters",
      city: "Pune",
      timings: "10:00 AM - 5:00 PM",
      price: "30.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Hair Cutting",
      businessName: "Urban Cuts",
      city: "Bangalore",
      timings: "10:00 AM - 8:00 PM",
      price: "20.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Plumbing",
      businessName: "PipeFixers",
      city: "Delhi",
      timings: "9:00 AM - 6:00 PM",
      price: "15.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Electrical Work",
      businessName: "WattWorks",
      city: "Pune",
      timings: "10:00 AM - 8:00 PM",
      price: "25.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Car Repair",
      businessName: "MechanicPro",
      city: "Mumbai",
      timings: "9:00 AM - 7:00 PM",
      price: "50.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Home Cleaning",
      businessName: "Shine and Sparkle",
      city: "Delhi",
      timings: "8:00 AM - 6:00 PM",
      price: "40.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Carpentry",
      businessName: "HandyCarp",
      city: "Bangalore",
      timings: "10:00 AM - 5:00 PM",
      price: "30.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Hair Cutting",
      businessName: "Elegant Styles",
      city: "Pune",
      timings: "10:00 AM - 8:00 PM",
      price: "20.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Plumbing",
      businessName: "Drain Masters",
      city: "Mumbai",
      timings: "9:00 AM - 6:00 PM",
      price: "15.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Electrical Work",
      businessName: "VoltFix",
      city: "Delhi",
      timings: "10:00 AM - 8:00 PM",
      price: "25.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Car Repair",
      businessName: "Rapid Auto",
      city: "Pune",
      timings: "9:00 AM - 7:00 PM",
      price: "50.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Home Cleaning",
      businessName: "NeatNest",
      city: "Bangalore",
      timings: "8:00 AM - 6:00 PM",
      price: "40.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Carpentry",
      businessName: "Crafty Carp",
      city: "Mumbai",
      timings: "10:00 AM - 5:00 PM",
      price: "30.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Hair Cutting",
      businessName: "SnipSnip Studio",
      city: "Delhi",
      timings: "10:00 AM - 8:00 PM",
      price: "20.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Plumbing",
      businessName: "LeakFix",
      city: "Bangalore",
      timings: "9:00 AM - 6:00 PM",
      price: "15.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Electrical Work",
      businessName: "PowerPro",
      city: "Mumbai",
      timings: "10:00 AM - 8:00 PM",
      price: "25.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Car Repair",
      businessName: "DriveFix Garage",
      city: "Bangalore",
      timings: "9:00 AM - 7:00 PM",
      price: "50.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Home Cleaning",
      businessName: "DustAway",
      city: "Pune",
      timings: "8:00 AM - 6:00 PM",
      price: "40.00",
    },
    {
      imgSrc: "https://via.placeholder.com/150",
      serviceName: "Carpentry",
      businessName: "FineWood Creations",
      city: "Delhi",
      timings: "10:00 AM - 5:00 PM",
      price: "30.00",
    },
  ];

  export default servicesData
  
  